services:
    _defaults:
        autowire: true
        autoconfigure: true

    WechatMiniProgramLogBundle\DataFixtures\:
        resource: '../../DataFixtures/*'
        tags: ['doctrine.fixture.orm']